# GitHub Actions to build and release a project
# Gigabyte B85M-GAMING-3 Hackintosh EFI

on:
  push:       
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

name: Uploud EFI to Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Package EFIs 
        run: |          
          zip -q -r B85M.dGPU.iMacPro1.1.zip . -i ./B85M\ dGPU\ \(iMacPro1\,1\)
          zip -q -r B85M.iGPU.iMac16.1.zip . -i ./B85M\ iGPU\ \(iMac16\,1\)
          ls -l *.zip
    
      - name: Create Release      
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          
      - name: Upload Release Asset        
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: GA-B85M-GAMING-3-${{github.ref}}-EFI
          tag_name: ${{ github.ref }}
          body_path: changelog.md
          prerelease: false
          files: |
            ./*.zip